### PR TITLE
copy code to clipboard

### PR DESCRIPTION
**Pull request by kalavt**

### CODE REVIEW

**Comment by arcanericky** [comment]
Thank you for the submission. I won't be merging as-is. A few things to think about...

Functionality already exists on various systems for copying the TOTP code to the clipbboard. For Windows you can pipe stdout to `Set-Clipboard` to get the code into the clipboard. With PowerShell it would be something like `totp mywebsite | Select-Clipboard`. For Linux, the same thing but using `xclip` with `totp mywebsite | xclip`. I'm not sure about MacOS since I don't have access to that at the moment, but it looks like this can be done by piping to `pbcopy`.

However, if you want to continue with this...

The code should not panic and exit early if the clipboard can't be created and initialized. Handle the error gracefully instead, thinking about how it can affect the various options. Using `panic` also makes the code tough to unit test because calling `panic` causes the test suite to immediately exit. Read on...

Think about what happens when you execute this code on a headless Linux machine for example (there exists command line only Windows systems that may not have a clipboard available as well). In this case there is no clipboard and the code panics and exits early.

```
$ totp mywebsite
615879
panic: clipboard unavailable: Failed to initialize the X11 display, and the clipboard package
will not work properly. Install the following dependency may help:

        apt install -y libx11-dev

If the clipboard package is in an environment without a frame buffer,
such as a cloud server, it may also be necessary to install xvfb:

        apt install -y xvfb

and initialize a virtual frame buffer:

        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99.0

Then this package should be ready to use.


goroutine 1 [running]:
github.com/arcanericky/totp/commands.copyToClipboard({0xc00001a4c0, 0x6})
        /home/user/Dev/Me/clipboard/commands/root.go:68 +0x57
github.com/arcanericky/totp/commands.generateCode({0x639da0, 0xc000014020}, {0x7ffce6fa85bc, 0x8}, {0x0?, 0x0?}, {0x0?, 0x0?, 0x773da0?})
        /home/user/Dev/Me/clipboard/commands/root.go:100 +0x377
github.com/arcanericky/totp/commands.run(0x0?, {0xc0000289c0, 0x1, 0x0?}, {{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, ...})
        /home/user/Dev/Me/clipboard/commands/root.go:224 +0x22f
github.com/arcanericky/totp/commands.getRootCmd.func2(0xc000004300?, {0xc0000289c0?, 0x1?, 0x1?})
        /home/user/Dev/Me/clipboard/commands/root.go:263 +0x3b
github.com/spf13/cobra.(*Command).execute(0xc000004300, {0xc000016050, 0x1, 0x1})
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x7e7
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/arcanericky/totp/commands.Execute()
        /home/user/Dev/Me/clipboard/commands/root.go:297 +0x5d
main.main()
        /home/user/Dev/Me/clipboard/cmd/totp/totp.go:10 +0x13
```

Something to keep in mind is when the user specifies the `--follow` option TOTP codes are generated and output to stdout every 30 seconds. You'll want to think about this and test with this option.

Copying to the clipboard should not be done by default and for every request. Some users may not want the TOTP code accessible in their clipboard (a security thing) or may be executing this on a headless system as above. Instead this functionality should be triggered with an option (example `--clipboard`).

I think this is enough feedback for now if you'd like to iterate on this.

**Comment by kalavt** [comment]
thanks for your time to response.
yes it cloud be done via piping to pbcopy
like this `totp okta | pbcopy`

I’ll close this MR directly as it’s meaning less to implement such function in *unix kind system.

**Comment by arcanericky** [comment]
I realize this is your second submission attempt. I do appreciate the effort. I do like this functionality because many users don't understanding piping. We would need more thought and unit testing around the implementation so it doesn't break things for current users. This goes especially for this type of change that's extremely OS dependent where GUI cross-platform functionality is needed. In many cases for CLI utilities like this giving the end user the tools (such as piping) to solve these problems can be the better answer.

**Comment by kalavt** [comment]
I was implemented a cmd like `totp setting autocopy true` to allow user define settings of this tool along of secrets section and store to `.totp-config.json `
Like:
`{
  setting:{
    autocopy: true
  },
  Secrets:…..
  ` 
but then realized that will make this software more and more complex.
as the simple small CLI tool to generate code, it’s better to keep it small, clean.

so then auto copy to clipboard functionality seems really redundant.

thanks for you sharing thoughts and BTW, it’s really a great nice tool.

**Pull request closed without merging**
