### PR TITLE
Update make for ARM-based architectures

### PR DESCRIPTION
**Pull request by pugmarx**
This would allow for binary generation for RaspberryPi

### CODE REVIEW

**Comment by arcanericky** [comment]
Thanks for your contribution @pugmarx. I am happy to accept your PR as is, but want to make sure you understand the following. Let me know.

Realize that your change is only in the `Makefile` and only affects development, not releases. In other words, your change doesn't add a Linux ARM32/ARM64 binary to the formal releases as it only affects the `Makefile` which is not used for formal releases.

If your intention is to get a released binary, we'll need to change up GoReleaser to allow for it. This can be done by making the appropriate modifications to [.goreleaser.yml](https://github.com/arcanericky/totp/blob/master/.goreleaser.yml). Getting the ARM64 releases should be easy enough and can be enabled by removing the following lines:

```
- goos: linux
  goarch: arm64
```

I'm not entirely sure what to do to enable the ARM32 releases. Right now only 64 binaries are being released, so adding something like the following might enable them:

```
goarch:
  - amd64
  - arm
  - arm64
```

You'll want to experiment with GoReleaser to to verify this works - and if not, to help determine what will work here.

**Comment by arcanericky** [comment]
No worries. I gave your changes a try and it's building a release for Windows/ARM64. While there's no harm in adding that, I'd rather not have extra binaries in the release if no one is using them. So if you will...

Add the following to the `ignore:` section in `.goreleaser.yml`:

```
- goos: windows
  goarch: arm
```

I'll approve and merge your PR after that, followed by creating a new release.

If you care to try to test it (and if you have GoReleaser installed), commit the change, add a tag, and build it with something like:

```
$ git commit -m 'Ignore Windows ARM releases'
$ git tag v1.2.3
$ GITHUB_TOKEN=123 goreleaser
```

Then it'll build and plop the releases into `dist/`, though publishing will fail - and that's fine.

**Comment by pugmarx** [comment]
Sure -- I have now tested it using `goreleaser` locally.

**Comment by arcanericky** [comment]
Thanks again. v1.0.8 has been released.

https://github.com/arcanericky/totp/releases/tag/v1.0.8

**Pull request merged**
